version: "3.9"

services:
  # 🍃 MongoDB Database
  mongo:
    image: mongo:6
    container_name: megamind-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # 📊 Optional: MongoDB Admin UI
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: megamind-mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password}
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME:-admin}:${MONGO_INITDB_ROOT_PASSWORD:-password}@mongo:27017/

  # 🧠 Backend: Express API
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: megamind-server
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: production
      PORT: 8080
      MONGODB_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME:-admin}:${MONGO_INITDB_ROOT_PASSWORD:-password}@mongo:27017/megamind?authSource=admin
    depends_on:
      - mongo

  # 🎨 Frontend: React PWA
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: megamind-client
    restart: always
    ports:
      - "5173:80" # frontend accessible on http://localhost:5173
    environment:
      - VITE_API_URL=http://localhost:8080
    depends_on:
      - server

volumes:
  mongo_data:
