services:
  mongo:
    image: mongo:6
    container_name: megamind-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express
    container_name: megamind-mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
    depends_on:
      - mongo

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: megamind-server
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: production
      PORT: 8080
      MONGO_URI: mongodb://${MONGO_INITDB_ROOT_USERNAME:-admin}:${MONGO_INITDB_ROOT_PASSWORD:-password}@mongo:27017/megamind?authSource=admin
    depends_on:
      - mongo

volumes:
  mongo-data:
